services:
  forum:
    container_name: forum
    image: forum:latest
    build: ./requirements
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - forum_db:/project/database

volumes:
  forum_db:
    name: forum_db
    driver: local
    driver_opts:
      type: none
      device: /home/ebelfkih/Desktop/zone\ 01\ project/forum/requirements/project/database/
      o: bind
