services:
  forum:
    build:
      context: ./requirements
      dockerfile: Dockerfile
    image: forum:latest
    container_name: forum
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./requirements/project/database:/project/database
      - ./requirements/project/logs:/project/logs

